blogyek/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pages.urls')),
    path('post/', include('posts.urls')),
    path('accounts/', include('users.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.LatestPostListView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView, name='contact'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList, name='posts'),
    path('create/', views.PostCreateView.as_view(), name='postCreate'),
    path('update/<slug:slug>/', views.PostUpdateView.as_view(), name='postUpdate'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='postDelete'),
    path('categories/<slug:category_slug>', views.PostList, name='posts_by_category'),
    path('tags/<slug:tag_slug>', views.PostList, name='posts_by_tag'),
    path('<slug:post_category_slug>/<int:id>/<slug:slug>/', views.PostDetailView.as_view(), name='postDetail'),
    path('search/', views.search, name='search'),
    path('comment/<int:pk>/', views.CommentView.as_view(), name='addComment'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path('register/', views.registerView, name='register'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
    path('profile/detail', views.ProfileDetailView.as_view(), name='viewProfile'),
    path('profile/update', views.ProfileUpdateView.as_view(), name='updateProfile'),
    path('change-password', views.PasswordsChangeView.as_view(template_name='change-password.html'), name='changePassword'),
    path('all/', views.AuthorIndexView.as_view(), name='authors'),
    path('detail/<int:pk>', views.AuthorDetailView.as_view(), name='authorDetail'),

]

posts/models.py
from ckeditor.fields import RichTextField
from django.conf import settings
from django.db import models


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='Kategori Adı')
    slug = models.SlugField(unique=True, help_text='Burayı manuel olarak değiştirmemeniz önerilir.')

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=50, verbose_name='Etiket Adı')
    slug = models.SlugField(unique=True, help_text='Burayı manuel olarak değiştirmemeniz önerilir.')

    def __str__(self):
        return self.name


class HitCount(models.Model):
    ip = models.CharField(max_length=100)

    def __str__(self):
        return self.ip


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True, verbose_name='Etiketler')
    views = models.ManyToManyField(HitCount, related_name='post_views', blank=True)
    title = models.CharField(max_length=75, verbose_name='Başlık')
    slug = models.SlugField(unique=True, help_text='Burayı manuel olarak değiştirmemeniz önerilir.')
    image = models.ImageField(upload_to='posts/%Y/%m/%d/', verbose_name='Görsel')
    content = RichTextField(verbose_name='İçerik')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')
    available = models.BooleanField(default=True, verbose_name='Aktif/Pasif')

    def __str__(self):
        return self.title

    def getHitCount(self):
        return self.views.count()

    class Meta:
        ordering = ['-created']


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField(verbose_name='Yorum')
    created = models.DateTimeField(auto_now_add=True)
    available = models.BooleanField(default=True, verbose_name='Aktif/Pasif')

    class Meta:
        ordering = ['-created']  ## Post yorumlarını yeniden eskiye sıralar

    def __str__(self):
        return self.author.username+' | '+ self.post.title

templates/partials/_base.html
{% load static %}



<!doctype html>
<html lang="en">
<head>
    <title>BlogYEK &mdash; Emre Kahriman</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300, 400,700|Inconsolata:400,700" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">

    <link rel="stylesheet" href="{% static 'fonts/ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">


    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="Site icon" type="image/png" href="{% static 'images/EK-NonCircle.png' %}"/>
</head>
<body>


<div class="wrap">
    <!-- Messages Start -->
    {% include 'partials/messages.html' %}
    <!-- Messages End -->

    <header role="banner">
        <div class="top-bar">
            <div class="container">
                <div class="row">
                    <div class="col-9 social">
                        <a href="#"><span class="fa fa-twitter"></span></a>
                        <a href="https://instagram.com/jupiterinvarisi"><span class="fa fa-instagram"></span></a>
                    </div>
                    <div class="col-3 search-top">
                        <!-- <a href="#"><span class="fa fa-search"></span></a> -->
                        <form action="{% url 'posts:search' %}" method="GET" class="search-top-form">
                            <span class="icon fa fa-search"></span>
                            <input type="text" name="query" id="s" placeholder="Type keyword to search...">
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="container logo-wrap">
            <div class="row pt-5">
                <div class="col-12 text-center">
                    <a class="absolute-toggle d-block d-md-none" data-toggle="collapse" href="#navbarMenu" role="button" aria-expanded="false" aria-controls="navbarMenu"><span class="burger-lines"></span></a>
                    <h1 class="site-logo"><a href="{% url 'pages:index' %}">Blogyek</a></h1>
                </div>
            </div>
        </div>

        <nav class="navbar navbar-expand-md  navbar-light bg-light">
            <div class="container">


                <div class="collapse navbar-collapse" id="navbarMenu">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item">
                            <a class="nav-link  {% if '/' == request.path %}active{% endif %}" href="{% url 'pages:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if 'post' in request.path and 'create' not in request.path %}active{% endif %}" href="{% url 'posts:posts' %}">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if 'accounts/all' in request.path or 'accounts/detail' in request.path %}active{% endif %}" href="{% url 'user:authors' %}">Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  {% if 'about' in request.path %}active{% endif %}" href="{% url 'pages:about' %}">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  {% if 'contact' in request.path %}active{% endif %}" href="{% url 'pages:contact' %}">Contact</a>
                        </li>
                        {% if request.user.is_authenticated %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle {% if 'profile' in request.path or 'change-password' in request.path or 'create' in request.path %}active{% endif %}" href="" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i> {{ request.user.username }}</a>
                                <div class="dropdown-menu" aria-labelledby="dropdown05">
                                    <a class="dropdown-item" href="{% url 'posts:postCreate' %}"><i class="fa fa-plus"></i> Create Post</a>
                                    <a class="dropdown-item" href="{% url 'user:viewProfile'%}"><i class="fa fa-id-card"></i> View Profile</a>
                                    <a class="dropdown-item" href="{% url 'user:updateProfile' %}"><i class="fa fa-pencil-square-o"></i> Update Profile</a>
                                    <a class="dropdown-item" href="{% url 'user:changePassword' %}"><i class="fa fa-wrench"></i> Change Password</a>
                                    <a class="dropdown-item" href="{% url 'user:logout' %}"><i class="fa fa-sign-out"></i> Logout</a>
                                </div>
                            </li>
                        {% else %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle {% if 'login' in request.path or 'register' in request.path %}active{% endif %}" href="" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
                                <div class="dropdown-menu" aria-labelledby="dropdown05">
                                    <a class="dropdown-item " href="{% url 'user:login' %}"><i class="fa fa-sign-in"></i> Login</a>
                                    <a class="dropdown-item " href="{% url 'user:register' %}"><i class="fa fa-user-plus"></i> Register</a>
                                </div>
                            </li>
                        {% endif %}
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <!-- END header -->


    {% block content %}
        <!-- Site Dynamic Content -->
    {% endblock %}


    <!-- Sidebar Section Start -->
    {% include 'partials/_sidebar.html' %}
    <!-- Sidebar Section End -->

    {% block related_posts %}
        <!-- (Optional) Related Post -->
    {% endblock %}

    <footer class="site-footer w-100 pb-4 pt-5">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h3>About Us</h3>
                    <p>Lorem ipsum dolor sit amet sa ksal sk sa, consectetur adipisicing elit. Ipsa harum inventore reiciendis. Ipsa harum inventore reiciendis.<a href="{% url 'pages:about' %}"><u>Read More</u></a> </p>
                </div>
            </div>
        </div>
    </footer>
    <!-- END footer -->

</div>

<!-- loader -->
<div id="loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214"/>
    </svg>
</div>

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.0.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>

<!-- added later -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/partials/_sidebar.html
{% load static %}



<div class="col-md-12 col-lg-4 sidebar">

    {% if popularposts %}
        <div class="sidebar-box">
            <h3 class="heading">Popular Posts</h3>
            <div class="post-entry-sidebar">
                <ul>

                    {% for popularpost in popularposts %}
                        <li>
                            <a href="{% url 'posts:postDetail' popularpost.category.slug popularpost.id popularpost.slug %}">
                                <img style="height: 55px" src="{{ popularpost.image.url }}" alt="popularpost img" class="mr-4">
                                <div class="text">
                                    <h4>{{ popularpost.title | title }}</h4>
                                    <div class="post-meta">
                                        <span>{{ popularpost.created | date }} &bullet;</span>
                                        <span><span class="fa fa-eye"></span> {{ popularpost.getHitCount }}</span>
                                    </div>
                                </div>
                            </a>
                        </li>
                    {% endfor %}


                </ul>
            </div>
        </div>
    {% endif %}
    <!-- END sidebar-box -->

    {% if categories %}
        <div class="sidebar-box">
            <h3 class="heading">Categories</h3>
            <ul class="categories">
                {% for category in categories %}
                    <li><a href="{% url 'posts:posts_by_category' category.slug %}">{{ category }} <span>({{ category.post_set.count }})</span></a></li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <!-- END sidebar-box -->

    {% if tags %}
        <div class="sidebar-box">
            <h3 class="heading">Tags</h3>
            <ul class="tags">
                {% for tag in tags %}
                    <li><a href="{% url 'posts:posts_by_tag' tag.slug %}">{{ tag }}</a></li>
                {% endfor %}

            </ul>
        </div>
    {% endif %}
</div>
<!-- END sidebar -->
</div>
</div>
</section>

templates/partials/mail_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Document</title>
</head>
<body>

    <div style="text-align: center;">
        <div style="margin-top: 40px;">
            <div>
                <div style="box-shadow: 0px 5px 5px rgb(0, 175, 0, .4);border-style: solid;border-color: rgb(0, 175, 0, .4); width: 90%; max-width: 700px; margin: 0 auto;">
                    <div style="border-bottom: solid rgb(0, 175, 0, .4);background-color: rgb(0, 175, 0, .4);"><h4 style="margin: 0;padding: 10px">From: {{ email }}</h4></div>
                    <div style="background-color: ">
                      <p style="padding: 2%;">{{ message }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/partials/messages.html
{% if messages %}
    <div style="z-index: 9999 !important;" aria-live="polite" aria-atomic="true" class="position-relative">
        <div class="toast-container position-absolute top-0 end-0 p-3">

            {% for message in messages %}
                <!-- MessageBox Start -->
                <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
                    <div class="toast-header border-{{ message.tags }}">
                        <strong class="me-auto text-{{ message.tags }}">{% if 'danger' in message.tags %}
                            Error!
                        {% elif 'warning' in message.tags %}
                            Warning!
                        {% elif 'success' in message.tags %}
                            Success!
                        {% elif 'info' in message.tags %}
                            Info!
                        {% endif %} </strong>
                        <small class="text-muted">just now</small>
                    </div>
                    <div class="toast-body">
                        {{ message }}
                    </div>
                </div>
                <!-- MessageBox End -->
            {% endfor %}

        </div>
    </div>
{% endif %}

{% if form.errors %}
    <div style="z-index: 9999 !important;" aria-live="polite" aria-atomic="true" class="position-relative">
        <div class="toast-container position-absolute top-0 end-0 p-3">

            {% for key, value in form.errors.items %}
                <!-- MessageBox Start -->
                <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
                    <div class="toast-header border-danger">
                        <strong class="me-auto text-danger">Error!</strong>
                        <small class="text-muted">just now</small>
                    </div>
                    <div class="toast-body">
                        {{ value }}
                    </div>
                </div>
                <!-- MessageBox End -->
            {% endfor %}

        </div>
    </div>
{% endif %}


<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        $('.toast').toast('show');
    });
</script>