blogyek/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pages.urls')),
    path('post/', include('posts.urls')),
    path('accounts/', include('users.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.LatestPostListView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView, name='contact'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList, name='posts'),
    path('create/', views.PostCreateView.as_view(), name='postCreate'),
    path('update/<slug:slug>/', views.PostUpdateView.as_view(), name='postUpdate'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='postDelete'),
    path('categories/<slug:category_slug>', views.PostList, name='posts_by_category'),
    path('tags/<slug:tag_slug>', views.PostList, name='posts_by_tag'),
    path('<slug:post_category_slug>/<int:id>/<slug:slug>/', views.PostDetailView.as_view(), name='postDetail'),
    path('search/', views.search, name='search'),
    path('comment/<int:pk>/', views.CommentView.as_view(), name='addComment'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path('register/', views.registerView, name='register'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
    path('profile/detail', views.ProfileDetailView.as_view(), name='viewProfile'),
    path('profile/update', views.ProfileUpdateView.as_view(), name='updateProfile'),
    path('change-password', views.PasswordsChangeView.as_view(template_name='change-password.html'), name='changePassword'),
    path('all/', views.AuthorIndexView.as_view(), name='authors'),
    path('detail/<int:pk>', views.AuthorDetailView.as_view(), name='authorDetail'),

]

posts/models.py
from ckeditor.fields import RichTextField
from django.conf import settings
from django.db import models


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='Kategori Adı')
    slug = models.SlugField(unique=True, help_text='Burayı manuel olarak değiştirmemeniz önerilir.')

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=50, verbose_name='Etiket Adı')
    slug = models.SlugField(unique=True, help_text='Burayı manuel olarak değiştirmemeniz önerilir.')

    def __str__(self):
        return self.name


class HitCount(models.Model):
    ip = models.CharField(max_length=100)

    def __str__(self):
        return self.ip


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True, verbose_name='Etiketler')
    views = models.ManyToManyField(HitCount, related_name='post_views', blank=True)
    title = models.CharField(max_length=75, verbose_name='Başlık')
    slug = models.SlugField(unique=True, help_text='Burayı manuel olarak değiştirmemeniz önerilir.')
    image = models.ImageField(upload_to='posts/%Y/%m/%d/', verbose_name='Görsel')
    content = RichTextField(verbose_name='İçerik')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')
    available = models.BooleanField(default=True, verbose_name='Aktif/Pasif')

    def __str__(self):
        return self.title

    def getHitCount(self):
        return self.views.count()

    class Meta:
        ordering = ['-created']


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField(verbose_name='Yorum')
    created = models.DateTimeField(auto_now_add=True)
    available = models.BooleanField(default=True, verbose_name='Aktif/Pasif')

    class Meta:
        ordering = ['-created']  ## Post yorumlarını yeniden eskiye sıralar

    def __str__(self):
        return self.author.username+' | '+ self.post.title

posts/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Count, Q
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.template.defaultfilters import slugify
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Post, Category, Tag, HitCount, Comment


# Create your views here.


class CommentView(LoginRequiredMixin, CreateView):
    template_name = 'comment_create.html'
    model = Comment
    fields = ['content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.post_id = self.kwargs['pk']
        messages.success(self.request, 'Comment successfully added.')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('posts:postDetail', args=(self.object.post.category.slug, self.object.post.pk, self.object.post.slug))


class PostCreateView(LoginRequiredMixin, CreateView):
    template_name = 'post_create.html'
    model = Post
    fields = ['category', 'tags', 'title', 'image', 'content']

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user
        post.slug = slugify(post.title)
        counter = 1
        temp_slug = post.slug

        while Post.objects.filter(
                slug=post.slug).exists():  # If there is the same information in the database, it is created by adding 1 to the end.
            post.slug = '{}-{}'.format(temp_slug, counter)
            counter += 1

        form.save()
        messages.success(self.request, 'Your post has been successfully created.')
        return super(PostCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('posts:postDetail', args=(self.object.category.slug, self.object.id, self.object.slug))


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'post_update.html'
    template_name_suffix = '_update_form'
    fields = ['category', 'tags', 'title', 'image', 'content']

    @method_decorator(login_required)  # If logged in this works
    def dispatch(self, request, *args, **kwargs):
        post = self.get_object()
        if post.author != self.request.user:
            raise Http404("You are not allowed to edit this Post")
        return super(PostUpdateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        post = form.save(commit=False)
        post.slug = slugify(post.title)
        counter = 1
        temp_slug = post.slug

        dbpost = Post.objects.get(id=post.id)
        if dbpost.title != post.title:  # Do these if the title of the post has changed
            while Post.objects.filter(
                    slug=post.slug).exists():  # If there is the same information in the database, it is created by adding 1 to the end.
                post.slug = '{}-{}'.format(temp_slug, counter)
                counter += 1

        form.save()
        messages.success(self.request, 'Your post has been successfully updated.')
        return super(PostUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('posts:postDetail', args=(self.object.category.slug, self.object.id, self.object.slug))


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('user:viewProfile')

    def get_object(self, queryset=None):
        post = super(PostDeleteView, self).get_object()
        if not post.author == self.request.user:
            raise Http404("You are not allowed to delete this Post")
        return post

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, 'Post successfully deleted.')
        return super(PostDeleteView, self).delete(request, *args, **kwargs)


def PostList(request, category_slug=None, tag_slug=None):
    category_page = None
    tag_page = None
    categories = Category.objects.all()
    tags = Tag.objects.all()
    popularposts = Post.objects.filter(available=True).annotate(viewyek=Count('views')).order_by('-viewyek')[:3]  # Get popular 3 posts
    context = {}

    if category_slug is not None:
        category_page = get_object_or_404(Category, slug=category_slug)
        posts = Post.objects.filter(available=True, category=category_page).order_by('-created')
        context.update({'title': 'Posts By Category'})
    elif tag_slug is not None:
        tag_page = get_object_or_404(Tag, slug=tag_slug)
        posts = Post.objects.filter(available=True, tags=tag_page).order_by('-created')
        context.update({'title': 'Posts By Tag'})
    else:
        posts = Post.objects.all().filter(available=True).order_by('-created')
        context.update({'title': 'All Posts'})

    paginator = Paginator(posts, 8)  # Show 8 object per page.
    page_number = request.GET.get('page')
    post_list = paginator.get_page(page_number)

    context.update({
        'post_list': post_list,
        'popularposts': popularposts,
        'categories': categories,
        'tags': tags,
    })
    return render(request, 'posts.html', context)


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


class PostDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # For Popular Posts
        context['popularposts'] = Post.objects.filter(available=True).annotate(viewyek=Count('views')).order_by('-viewyek')[:3]  # Get popular 3 posts

        context['relatedposts'] = Post.objects.filter(available=True, category__name=self.object.category.name).annotate(viewyek=Count('views')).order_by('-viewyek')[:3]  # Get related 3 popular posts

        context['categories'] = Category.objects.all()
        context['tags'] = Tag.objects.all()
        context['comments'] = Comment.objects.filter(available=True, post_id=self.object.id).order_by('-created')[:10]  # Get last 10 comments
        return context

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        ip = get_client_ip(self.request)
        if HitCount.objects.filter(ip=ip).exists():
            pass
        else:
            HitCount.objects.create(ip=ip)
        post = Post.objects.get(pk=self.object.pk)
        post.views.add(HitCount.objects.get(ip=ip))
        return self.render_to_response(context)


def search(request):
    posts = Post.objects.filter(Q(title__icontains=request.GET['query']) |
                                Q(content__icontains=request.GET['query']))
    categories = Category.objects.all()
    tags = Tag.objects.all()
    context = {
        'post_list': posts,
        'categories': categories,
        'tags': tags,
        'title': 'Search Results'
    }
    return render(request, 'posts.html', context)

templates/authors.html
{% extends 'partials/_base.html' %}
{% load static %}


{% block content %}

    <section class="site-section py-sm pt-5">
    <div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2 class="mb-4">All Authors</h2>
        </div>
    </div>
    <div class="row blog-entries">
    <div class="col-md-12 col-lg-8 main-content">
        <div class="row pt-5">




            {% if author_list %}
                {% for author in author_list %}
                    <div class="col-md-6">
                        <div class="sidebar-box shadow shadow-sm element-animate">
                            <div class="bio text-center">
                                <img src="{{ author.userdetail.image.url }}" alt="{{ author.username }} Image" class="img-fluid">
                                <div class="bio-body">
                                    <h2>
                                        {% if author.get_full_name %}
                                            {{ author.get_full_name | truncatechars:15 }}
                                        {% else %}
                                            {{ author.username | title }}
                                        {% endif %}{% if author.userdetail.title %} - <span style="font-weight: lighter; font-size: 17px" class="font-italic">{{ author.userdetail.title }}</span> {% endif %}
                                    </h2>
                                    <p class="mb-3">{% if author.userdetail.description %}
                                        {{ author.userdetail.description|truncatechars:65 }}
                                    {% endif %} </p>
                                    <p>
                                    <div class="col-md-12 text-center text-capitalize" style="height:40px">
                                        <a onmouseover='$(this).addClass("btn btn-sm btn-primary")' onmouseout='$(this).removeClass("btn btn-sm btn-primary")' href="{% url 'user:authorDetail' author.pk %}"> Read My Bio <i class="fa fa-arrow-right"></i></a>
                                    </div>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="col-md-12 ">
                    <div class="alert alert-primary" role="alert">
                        The author to be listed was not found!
                    </div>
                </div>
            {% endif %}



        </div>

        <div class="row mt-5">
            <div class="col-md-12 text-center">
                <nav aria-label="Page navigation" class="text-center">
                    <ul class="pagination">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                                <a class="font-weight-bold" href="?page=1">&laquo;First</a>
                                <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
                            {% endif %}

                            <span class="current">
                                    Page <span class="font-weight-bold">{{ page_obj.number }}</span> of {{ page_obj.paginator.num_pages }}.
                            </span>

                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}">Next</a>
                                <a class="font-weight-bold" href="?page={{ page_obj.paginator.num_pages }}">Last&raquo;</a>
                            {% endif %}
                        </span>
                    </ul>
                </nav>
            </div>
        </div>





    </div>
    <!-- END main-content -->


{% endblock %}
</div>
</div>
</section>

templates/change-password.html
{% extends 'partials/_base.html' %}
{% load static %}



{% block content %}
    <section class="site-section">
    <div class="container">
    <div class="row mb-4">
        <div class="col-md-6 offset-md-3">
            <h1>Change Password Form</h1>
        </div>
    </div>
    <div class="row blog-entries">
    <div class="col-md-12 col-lg-8 offset-lg-2 main-content">

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-12 form-group">
                    <label for="first_name">Old Password</label>
                    {{ form.old_password }}
                </div>
                <div class="col-md-12 form-group">
                    <label for="last_name">New Password</label>
                    {{ form.new_password1 }}
                </div>
                <div class="col-md-12 form-group">
                    <label for="username">Confirm New Password</label>
                    {{ form.new_password2 }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 form-group">
                    <input type="submit" value="Update Password" class="btn btn-primary rounded">
                </div>
            </div>
            <style>
                .no-list{
                    list-style: none;
                }
            </style>
        </form>
    </div>

    <!-- END main-content -->

    <script>
        $( "#id_old_password" ).addClass( "form-control" );
        $( "#id_new_password1" ).addClass( "form-control" );
        $( "#id_new_password2" ).addClass( "form-control" );

        $(".errorlist").addClass("no-list pl-0")
    </script>
{% endblock %}

templates/index.html
{% extends 'partials/_base.html' %}
{% load static %}


{% block content %}
    <!-- SLIDER section -->
    <section class="site-section pt-5 pb-5">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="owl-carousel owl-theme home-slider">

                        {% for randompost in randomposts %}
                            <div>
                                <a href="{% url 'posts:postDetail' randompost.category.slug randompost.id randompost.slug %}" class="a-block d-flex align-items-center height-lg" style="background-image: url({{ randompost.image.url }});">
                                    <div class="text half-to-full">
                                        <span class="category mb-5">{{ randompost.category.name }}</span>
                                        <div class="post-meta">
                                            <span class="author mr-2"><img src="{{ randompost.author.userdetail.image.url }}" alt="Colorlib"> {{ randompost.author.username }}</span>&bullet;
                                            <span class="mr-2">{{ randompost.created | date }} </span> &bullet;
                                            <span class="ml-2"><span class="fa fa-eye"></span> {{ randompost.getHitCount }}</span>
                                        </div>
                                        <h3>{{ randompost.title | title }}</h3>
                                        <p>{{ randompost.content | safe | linebreaks | truncatechars:100 }}</p>
                                    </div>
                                </a>
                            </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- END section -->

    <style>
        @media screen and (max-width: 524px) {
            .spanyek{
                height: auto !important;
            }
            .spanyek p{
                display: none !important;
            }
            .catyek{
                display: none !important;
            }
        }
    </style>

    <section class="site-section pt-0 pb-3">
    <div class="container">
    <div class="row mb-4">
        <div class="col-md-6">
            <h2 class="mb-4">Latest Posts</h2>
        </div>
    </div>
    <div class="row blog-entries">
    <div class="col-md-12 col-lg-8 main-content">
        <div class="row mb-5">
            <div class="col-md-12">
                {% if latestposts %}
                    {% for latestpost in latestposts %}
                        <div class="post-entry-horzontal ">
                            <a style="width: 100%" href="{% url 'posts:postDetail' latestpost.category.slug latestpost.id latestpost.slug %}">
                                <div class="image element-animate " data-animate-effect="fadeIn" style="background-image: url({{ latestpost.image.url }});"></div>
                                <span class="text spanyek">
                                    <div class="post-meta ">
                                        <span class="author"><img src="{{ latestpost.author.userdetail.image.url }}" alt="Colorlib"> {{ latestpost.author.username | title }} &bullet; </span>
                                        <span>{{ latestpost.created | date }} &bullet;</span>
                                        <span class="catyek">{{ latestpost.category.name }} &bullet;</span>
                                        <span><span class="fa fa-eye"></span> {{ latestpost.getHitCount }}</span>
                                    </div>
                                    <h2>{{ latestpost.title | title}}</h2>
                                    <p class="mb-0">{{ latestpost.content|safe|linebreaks|truncatechars:100 }}</p>
                                </span>
                            </a>
                        </div>
                        <!-- END post -->
                    {% endfor %}
                {% else %}
                    <div class="alert alert-primary" role="alert">
                        The article to be listed was not found!
                    </div>
                {% endif %}


                <!-- Show All Posts Link YEK -->
                <div class="row mb-3">
                    <div class="col-md-12 text-center text-capitalize" style="height:40px">
                        <a onmouseover='$(this).addClass("btn btn-sm btn-primary")' onmouseout='$(this).removeClass("btn btn-sm btn-primary")' href="{% url 'posts:posts' %}"> Show All Posts <i class="fa fa-arrow-right"></i></a>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <!-- END main-content -->
{% endblock %}

templates/login.html
{% extends 'partials/_base.html' %}
{% load static %}


{% block content %}
    <section class="site-section">
    <div class="container">
    <div class="row mb-4">
        <div class="col-md-6">
            <h1>Login Form</h1>
        </div>
    </div>
    <div class="row blog-entries">
    <div class="col-md-12 col-lg-8 main-content">

        <form action="{% url 'user:login' %}" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-12 form-group">
                    <label for="username">Username</label>
                    <input type="text" id="username" name="username" class="form-control" required>
                </div>
                <div class="col-md-12 form-group">
                    <label for="password">Password</label>
                    <input type="password" id="password" name="password" class="form-control" required>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 form-group">
                    <input type="submit" value="Sign In" class="btn btn-primary">
                </div>
            </div>
        </form>


    </div>

    <!-- END main-content -->


{% endblock %}

templates/post_delete.html
{% extends 'partials/_base.html' %}
{% load static %}



{% block content %}
    <section class="site-section">
        <div class="container">
            <div class="row mb-4">
                <div class="col-md-6 offset-md-3">
                    <h1>Post Delete Confirmation</h1>
                </div>
            </div>
            <div class="row blog-entries">
                <div class="col-md-12 col-lg-8 offset-lg-2 main-content">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <div class="card border-warning mb-3">
                            <div class="card-header ">Warning!</div>
                            <div class="card-body">
                                <h5 class="card-title">Post Delete Process</h5>
                                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                            </div>
                            <div class="card-footer text-end">
                                <button onclick="{% url 'pages:index' %}" class="btn btn-secondary btn-sm">Close</button>
                                <input type="submit" class="btn btn-danger btn-sm" value="Delete" >
                            </div>
                        </div>
                    </form>
                </div>
                <script>
                    $('input, select').addClass('form-control');
                    $('textarea').attr('cols','100').addClass('form-control');
                    $('input[type="submit"]').removeClass('form-control');
                </script>

                <!-- END main-content -->


{% endblock %}

templates/post_detail.html
{% extends 'partials/_base.html' %}
{% load static %}



{% block content %}
    <section class="site-section py-lg">
    <div class="container">

    <div class="row blog-entries element-animate">

    <div class="col-md-12 col-lg-8 main-content">
        <img src="{{ post.image.url }}" alt="Image" class="img-fluid mb-5 w-100">
        <div class="post-meta">
            <span class="author"><img src="{{ post.author.userdetail.image.url }}" alt="Colorlib" class="mr-2"> {{ post.author.username | title }} &bullet; </span>
            <span>{{ post.created | date }} &bullet;</span>
            <span class="catyek">{{ post.category.name }}  &bullet;</span>
            <span><span class="fa fa-eye"></span> {{ post.getHitCount }}</span>
        </div>
        <h1 class="mb-1">{{ post.title | title }}</h1>
        <a class="category mb-3" href="{% url 'posts:posts_by_category' post.category.slug %}">{{ post.category.name }}</a>

        <style>
            @media screen and (max-width: 524px) {
                .catyek{
                    display: none !important;
                }
            }
        </style>

        <div class="post-content-body mb-5">
            <p>{{ post.content | safe | linebreaks }}</p>
        </div>
        <br>
        <div class="row mt-3 ">
            <div class="col-md-12">
                <div class="sidebar-box shadow shadow-sm">
                    <div class="bio text-center">
                        <img style="height: 130px; width: 130px!important; max-width: 130px" src="{{ post.author.userdetail.image.url }}" class="img-fluid">
                        <div class="bio-body">
                            <h2>
                                {% if post.author.get_full_name %}
                                    {{ post.author.get_full_name }}
                                {% else %}
                                    {{ post.author.username | title }}
                                {% endif %}{% if post.author.userdetail.title %} - <span style="font-weight: lighter; font-size: 17px" class="font-italic">{{ post.author.userdetail.title }}</span> {% endif %}
                            </h2>
                            <p class="mb-4">{% if post.author.userdetail.description %}{{ post.author.userdetail.description }}{% endif %}</p>
                            <!-- <p><a href="#" class="btn btn-outline-primary btn-sm rounded">Read my bio</a></p> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="pt-5">
            <p>Category:  <a href="{% url 'posts:posts_by_category' post.category.slug %}">{{ post.category.name }}</a>  {% if post.tags.all %}Tags: {% for tag in post.tags.all %} <a href="{% url 'posts:posts_by_tag' tag.slug %}">#{{ tag.slug }}</a>{% if not forloop.last %},{% endif %}{% endfor %}{% endif %}</p>
        </div>


        <div class="pt-5">
            <h3 class="mb-5">{{ comments.count }} Comments</h3>
            <ul class="comment-list">

                {% if comments %}
                    {% for comment in comments %}
                        <li class="comment">
                            <div class="vcard">
                                <img src="{{ comment.author.userdetail.image.url }}" alt="Image placeholder">
                            </div>
                            <div class="comment-body">
                                <h3>{% if comment.author.get_full_name %}
                                    {{ comment.author.get_full_name }}
                                {% else %}
                                    {{ comment.author.username }}
                                {% endif %} </h3>
                                <div class="meta">{{ post.created }}</div>
                                <p>{{ comment.content }}</p>
                            </div>
                        </li>
                    {% endfor %}
                {% else %}
                    <div class="alert alert-primary" role="alert">
                        This article has not been commented yet, write the first comment!
                    </div>
                {% endif %}

            </ul>
            <!-- END comment-list -->




            {% if request.user.is_authenticated %}
                <div class="comment-form-wrap pt-5 text-center">
                    {#                    <h3 class="mb-5">Leave a comment</h3>#}
                    <!-- Post Comment Link YEK -->
                    <div class="row mb-3">
                        <div class="col-md-12 text-center text-capitalize" style="height:40px">
                            <a onmouseover='$(this).addClass("btn btn-sm btn-primary")' onmouseout='$(this).removeClass("btn btn-sm btn-primary")' href="{% url 'posts:addComment' post.id %}"> Leave a comment <i class="fa fa-arrow-right"></i></a>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>

    <!-- END main-content -->
{% endblock %}



{% block related_posts %}
    <section class="py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="mb-3 ">Related Post</h2>
                </div>
            </div>
            <div class="row">


                {% for relatedpost in relatedposts %}
                    <div class="col-md-6 col-lg-4">
                        <a href="#" class="a-block sm d-flex align-items-center height-md" style="background-image: url({{ relatedpost.image.url }}); ">
                            <div class="text">
                                <div class="post-meta">
                                    <span class="category">{{ relatedpost.category.name }}</span>
                                    <span class="mr-2">{{ relatedpost.created | date }}</span> &bullet;
                                    <span class="ml-2"><span class="fa fa-eye"></span> {{ relatedpost.getHitCount }}</span>
                                </div>
                                <h3>{{ relatedpost.title }}</h3>
                            </div>
                        </a>
                    </div>
                {% endfor %}



            </div>
        </div>


    </section>
    <!-- END section -->
{% endblock %}